backend:
  name: github
  repo: cafecommapa/cafecommapa.github.io
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Autor", name: "criador", widget: "select", options: ["Marcia Shimada", "Carlos Patrocinio"] }
      - { label: "Categoria", name: "category", widget: "select", options: ["viagem", "pensamento", "livro", "receita", "filme", "tecnologia"] }
      - { label: "Resumo", name: "summary", widget: "text", required: false }
      - { label: "Imagem", name: "cover", widget: "image", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
